// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzVporRzxe5rVUKpaaoLOYxnTgCdF4Vf8',
    appId: '1:1015015852444:web:65cdc745fe84294c856059',
    messagingSenderId: '1015015852444',
    projectId: 'phone-auth-e5dce',
    authDomain: 'phone-auth-e5dce.firebaseapp.com',
    storageBucket: 'phone-auth-e5dce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjjy2HAFx3zjiId_CxQVO6P0PLpYhq_l8',
    appId: '1:1015015852444:android:ef30f2cc77796d52856059',
    messagingSenderId: '1015015852444',
    projectId: 'phone-auth-e5dce',
    storageBucket: 'phone-auth-e5dce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Ki083MLmEZSuvlNlBTa-mu495O9njhM',
    appId: '1:1015015852444:ios:9aca389856f10b0b856059',
    messagingSenderId: '1015015852444',
    projectId: 'phone-auth-e5dce',
    storageBucket: 'phone-auth-e5dce.appspot.com',
    iosBundleId: 'com.example.craftMyPlate',
  );
}
